import React, { useState } from 'react';
import type { AISummary, AIFactCheck } from '../data/mockData';
import { AiOutlineCheckCircle, AiOutlineDownload, AiOutlineWarning, AiOutlineCloseCircle, AiOutlineLoading3Quarters, AiOutlineThunderbolt } from 'react-icons/ai';
import { BsRobot } from 'react-icons/bs';
import { localLlmService } from '../services/localLlmService';

interface AICompanionProps {
    summary?: AISummary;
    factChecks?: AIFactCheck[];
    videoTitle: string;
    transcript?: string;
}

const AICompanion: React.FC<AICompanionProps> = ({ summary: initialSummary, factChecks: initialFactChecks, videoTitle, transcript }) => {
    const [activeTab, setActiveTab] = useState<'summary' | 'facts'>('summary');

    // Data State
    const [summary, setSummary] = useState<AISummary | undefined>(initialSummary);
    const [factChecks, setFactChecks] = useState<AIFactCheck[] | undefined>(initialFactChecks);

    // Loading/Error State
    const [loading, setLoading] = useState(false);
    const [progress, setProgress] = useState(0); // For model downloading
    const [error, setError] = useState<string | null>(null);

    const handleGenerate = async () => {
        if (!transcript) return;
        setLoading(true);
        setError(null);
        setProgress(0);

        try {
            if (activeTab === 'summary') {
                // Ensure model is loaded first (simulated progress for UX if quick)
                await localLlmService.loadModels((p) => setProgress(p));

                const summaryText = await localLlmService.generateSummary(transcript);

                setSummary({
                    summaryText,
                    keywords: [], // Simplification for local model
                    takeaways: ["Generated seamlessly on your device.", "No data sent to the cloud."]
                });
            } else {
                const claims = await localLlmService.extractClaims(transcript);
                // Map to AIFactCheck format
                setFactChecks(claims.map(c => ({
                    timestamp: c.timestamp,
                    claim: c.claim,
                    status: c.status as 'correct' | 'incorrect' | 'disputed'
                })));
            }
        } catch (err: any) {
            setError(err.message || "Failed to run local AI model.");
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    const handleExport = () => {
        if (!summary) return;

        const date = new Date().toLocaleDateString();
        const content = `
# AI Summary: ${videoTitle}
Date: ${date}

## Summary
${summary.summaryText}

---
Generated by Free Local AI
        `;

        const blob = new Blob([content], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `Summary-${videoTitle.replace(/\s+/g, '-')}.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="ai-companion">
            <div className="ai-header">
                <BsRobot size={20} />
                <span>AI Companion (Free & Local)</span>
                <div className="ai-tabs">
                    <button
                        className={`ai-tab ${activeTab === 'summary' ? 'active' : ''}`}
                        onClick={() => setActiveTab('summary')}
                    >
                        Summary
                    </button>
                    <button
                        className={`ai-tab ${activeTab === 'facts' ? 'active' : ''}`}
                        onClick={() => setActiveTab('facts')}
                    >
                        Fact Check
                    </button>
                </div>
            </div>

            <div className="ai-content-wrapper">
                {error && (
                    <div className="error-msg">
                        <AiOutlineWarning /> {error}
                    </div>
                )}

                <div className="ai-content">
                    {loading ? (
                        <div className="loading-placeholder">
                            <AiOutlineLoading3Quarters className="spin" size={30} />
                            <p>
                                {progress > 0 && progress < 100
                                    ? `Downloading AI Model... ${Math.round(progress)}%`
                                    : "Thinking..."}
                            </p>
                            <span className="sub-text">Running strictly on your device.</span>
                        </div>
                    ) : (
                        <>
                            {activeTab === 'summary' && (
                                <div className="summary-view">
                                    {summary ? (
                                        <>
                                            <div className="section">
                                                <h3>Overview</h3>
                                                <p>{summary.summaryText}</p>
                                            </div>
                                            <div className="section">
                                                <h3>Notes</h3>
                                                <ul className="takeaways-list">
                                                    {summary.takeaways.map((t, i) => <li key={i}>{t}</li>)}
                                                </ul>
                                            </div>
                                            <button className="export-btn" onClick={handleExport}>
                                                <AiOutlineDownload size={18} />
                                                Save Notes
                                            </button>
                                        </>
                                    ) : (
                                        <div className="empty-state">
                                            <div className="icon-wrapper">
                                                <AiOutlineThunderbolt size={24} />
                                            </div>
                                            <p>Generate a summary instantly using local AI.</p>
                                            <button className="generate-btn" onClick={handleGenerate}>
                                                Start Analysis
                                            </button>
                                        </div>
                                    )}
                                </div>
                            )}

                            {activeTab === 'facts' && (
                                <div className="facts-view">
                                    {factChecks ? (
                                        <div className="facts-list">
                                            {factChecks.map((check, i) => (
                                                <div key={i} className={`fact-card ${check.status}`}>
                                                    <div className="fact-top">
                                                        <span className="timestamp">{check.timestamp}</span>
                                                        {check.status === 'correct' && <span className="status-badge correct"><AiOutlineCheckCircle /> Verified</span>}
                                                        {check.status === 'incorrect' && <span className="status-badge incorrect"><AiOutlineCloseCircle /> Incorrect</span>}
                                                        {check.status === 'disputed' && <span className="status-badge disputed"><AiOutlineWarning /> Disputed</span>}
                                                    </div>
                                                    <p className="claim">"{check.claim}"</p>
                                                </div>
                                            ))}
                                        </div>
                                    ) : (
                                        <div className="empty-state">
                                            <div className="icon-wrapper">
                                                <AiOutlineThunderbolt size={24} />
                                            </div>
                                            <p>Verify claims in this video locally.</p>
                                            <button className="generate-btn" onClick={handleGenerate}>
                                                Start Fact Check
                                            </button>
                                        </div>
                                    )}
                                </div>
                            )}
                        </>
                    )}
                </div>
            </div>

            <style>{`
                .ai-companion {
                    background: #1f1f1f;
                    border-radius: 12px;
                    overflow: hidden;
                    border: 1px solid #333;
                    display: flex;
                    flex-direction: column;
                    margin-bottom: 20px;
                }

                .ai-header {
                    padding: 12px 16px;
                    background: linear-gradient(90deg, #1a1a1a, #252525);
                    border-bottom: 1px solid #333;
                    display: flex;
                    align-items: center;
                    gap: 12px;
                    font-weight: 600;
                    color: #2ba640; /* Green for "Free/Local" */
                    flex-wrap: wrap;
                }

                .ai-tabs {
                    display: flex;
                    gap: 8px;
                    margin-left: auto;
                }

                .ai-tab {
                    background: transparent;
                    border: none;
                    color: #aaa;
                    cursor: pointer;
                    font-size: 13px;
                    padding: 4px 8px;
                    border-radius: 4px;
                    transition: all 0.2s;
                }

                .ai-tab:hover {
                    color: white;
                    background: rgba(255,255,255,0.1);
                }

                .ai-tab.active {
                    color: white;
                    background: #2ba640;
                    font-weight: 500;
                }

                .ai-content {
                    padding: 16px;
                    max-height: 400px;
                    overflow-y: auto;
                }

                .section {
                    margin-bottom: 20px;
                }

                .section h3 {
                    font-size: 14px;
                    color: #ddd;
                    margin-bottom: 8px;
                    text-transform: uppercase;
                    letter-spacing: 0.5px;
                }

                .section p {
                    font-size: 14px;
                    color: #bbb;
                    line-height: 1.5;
                }

                .takeaways-list {
                    list-style: disc;
                    padding-left: 20px;
                    color: #bbb;
                    font-size: 14px;
                }

                .takeaways-list li {
                    margin-bottom: 6px;
                }

                .export-btn {
                    width: 100%;
                    padding: 10px;
                    background: #2a2a2a;
                    border: 1px solid #444;
                    color: white;
                    border-radius: 8px;
                    cursor: pointer;
                    display: flex;
                    justify-content: center;
                    align-items: center;
                    gap: 8px;
                    transition: background 0.2s;
                    margin-top: 10px;
                }

                .export-btn:hover {
                    background: #333;
                    border-color: #555;
                }

                .loading-placeholder {
                    text-align: center;
                    padding: 40px;
                    color: #666;
                    display: flex;
                    flex-direction: column;
                    align-items: center;
                    gap: 16px;
                }
                
                .sub-text {
                    font-size: 12px;
                    color: #444;
                }
                
                .spin {
                    animation: spin 1s linear infinite;
                }
                
                @keyframes spin { 100% { -webkit-transform: rotate(360deg); transform:rotate(360deg); } }

                .generate-btn {
                    background: #2ba640;
                    color: white;
                    border: none;
                    padding: 10px 24px;
                    border-radius: 24px;
                    font-size: 14px;
                    font-weight: 600;
                    cursor: pointer;
                    display: flex;
                    align-items: center;
                    gap: 8px;
                    margin: 16px auto;
                    transition: transform 0.2s;
                }
                
                .generate-btn:hover {
                    background: #238b34;
                    transform: scale(1.05);
                }
                
                .icon-wrapper {
                    width: 50px;
                    height: 50px;
                    border-radius: 50%;
                    background: rgba(43, 166, 64, 0.1);
                    color: #2ba640;
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    margin: 0 auto 12px auto;
                }

                /* Fact Check Styles */
                .facts-list {
                    display: flex;
                    flex-direction: column;
                    gap: 12px;
                }

                .fact-card {
                    padding: 12px;
                    border-radius: 8px;
                    border-left: 4px solid #555;
                    background: #252525;
                }

                .fact-card.correct { border-left-color: #2ba640; background: rgba(43, 166, 64, 0.1); }
                .fact-card.incorrect { border-left-color: #d93025; background: rgba(217, 48, 37, 0.1); }
                .fact-card.disputed { border-left-color: #f9ab00; background: rgba(249, 171, 0, 0.1); }

                .fact-top {
                    display: flex;
                    justify-content: space-between;
                    margin-bottom: 6px;
                    font-size: 12px;
                }

                .timestamp {
                    color: #3ea6ff;
                    font-family: monospace;
                    background: rgba(62, 166, 255, 0.1);
                    padding: 2px 6px;
                    border-radius: 4px;
                }

                .status-badge {
                    display: flex;
                    align-items: center;
                    gap: 4px;
                    font-weight: 600;
                }

                .status-badge.correct { color: #2ba640; }
                .status-badge.incorrect { color: #d93025; }
                .status-badge.disputed { color: #f9ab00; }

                .claim {
                    font-size: 14px;
                    color: #ddd;
                    margin-bottom: 0;
                }
                
                .error-msg {
                    background: rgba(217, 48, 37, 0.1);
                    color: #ff4e45;
                    padding: 10px;
                    margin: 10px 16px;
                    border-radius: 4px;
                    font-size: 13px;
                    display: flex;
                    align-items: center;
                    gap: 8px;
                }
                
                .empty-state {
                    text-align: center;
                    color: #666;
                    padding: 40px 20px;
                }
            `}</style>
        </div>
    );
};

export default AICompanion;
